image: alpine/latest
packages:
  - uv
  - curl
  - gcc
  - python3-dev
#  - libffi-dev
#  - musl-dev
#  - openssl-dev
#  - postgresql-dev

secrets:
  - b88a4c2c-944c-42a6-9fbb-7483049c458a

sources:
  - git@git.sr.ht:~sfermigier/lewaf

tasks:
  - install: |
      cd lewaf
      uv sync
  - test: |
      cd lewaf
      uv run pytest
  - lint: |
      cd lewaf
      uv run ruff check src tests
      uv run mypy src
  - nox: |
      cd lewaf
      uvx nox

triggers:
  - action: email
    condition: failure
    to: sf@fermigier.com
